source 'https://rubygems.org'

gem 'dotenv'
gem 'google_search_results'
gem 'pg'
gem 'pinecone'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'ruby-openai'
gem 'tiktoken_ruby'
gem 'tty-spinner'
gem 'uuidtools'
